version: "2"

services:

  ansible:
    build:
      context: ../
      dockerfile: Dockerfile 
    env_file:
      - ./common.env
    volumes:
      - ../source/hosts:/etc/ansible/hosts
      - ../source/troposphere:/etc/ansible/troposphere
      - ../source/playbooks:/etc/ansible/playbooks
      - ../source/www:/www
      - ../source/ansible.cfg:/etc/ansible/ansible.cfg
    command: bash -c "echo 'welcome'; tail -f /dev/null"

# networks:
  # back-tier:
  # front-tier:
# volumes:
  # db-data:
